// <auto-generated />
using CityInfo.APi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityInfo.APi.Migrations
{
    [DbContext(typeof(CityInfocontext))]
    partial class CityInfocontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityInfo.APi.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("City");

                    b.HasData(
                        new { ID = 1, Description = " Capital of Sri Lanka and Business city", Name = " Colombo" },
                        new { ID = 2, Description = " Famous For Beautiful Beaches", Name = " Negambo " },
                        new { ID = 3, Description = " The most beautiful part of Sri Lanka with beautiful climate", Name = " NuwaraEliya " },
                        new { ID = 4, Description = " The Most Developing City Of Sri Lanka", Name = " Badulla " }
                    );
                });

            modelBuilder.Entity("CityInfo.APi.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new { ID = 1, CityId = 1, Description = " A beautiful beach and picnic spot in the center of colombo", Name = " Galle Face" },
                        new { ID = 2, CityId = 1, Description = " A beautiful place for beach lovers", Name = " Mount Lavina" },
                        new { ID = 3, CityId = 2, Description = " Foregin Tourist Attraction Point", Name = " Spatty Moty" },
                        new { ID = 4, CityId = 3, Description = " A beautiful park in NuwaraEliya", Name = " Goergia Park" },
                        new { ID = 5, CityId = 4, Description = " A beautiful university of Sri Lanka ", Name = " Uva Wellassa" }
                    );
                });

            modelBuilder.Entity("CityInfo.APi.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.APi.Entities.City", "City")
                        .WithMany("PointOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
